### ISSUE TITLE
Huuuuge Numbers to String.

### ISSUE THREAD

**Issue by kakadais** [kshji/go#1]
Hey- 
I should change to use this repo from the original one.

Do you have an idea for the number to string formatting?
A small number is okay but a long number such as '1114012700100530002020472' is formatting as exponential numbers.
I just want to change all fields to string with any data.

**Comment by kshji** [comment]
Even I use this tool also almost every week, I haven't edited in a long time. So it's little heavy to remember how the core has done and what rewriting I have done. 

I guess the main problem is used tealeg version.  

I  have used xlsx@v1.0.3 in my development and not updated tealeg after that. I know that I need make some or more rewriting if I update tealeg. Not so nice feature in some libraries. That's the main reason why I have not used newer library. I feel that using newer library and rewriting benefit is zero.

But I remember how I have made solution: I use excel template where I set all attributes as I need and use it. Or config file.

It works also without template:
data5.csv
```
id;str;longnum;longnum2[i]
1;111;11111111111111111111111;11111111111111111111111
1;111;'11111111111111111111111;11111111111111111111111111111111111
1;111;1114012700100530002020472;1114012700100530002020472
```

`csv2xlsx  -o data5.xlsx data5.csv`

Without template or typing in headers: default is to "quess" type: numbers even it's very long: with 2 decimals.

Or using config (data5.cfg), I have not tested this how it works with never tealeg.
```
{
  "font": "bembo",
  "fontsize": "11",
  "formatdate": "d.m.yyyy",
  "formatnumber": "#,##0.0000",
  "cols": [
    {
      "colname": "id",
      "type": "int",
      "font": "helvetica",
      "fontsize": "12",
      "align": "right",
      "width": "10"
    },
    {
      "colname": "str",
      "type": "text"
    },
    {
      "colname": "longnum",
      "type": "int"
    },
    {
      "colname": "longnum2",
      "type": "text",
      "font": "arial",
      "fontsize": "9",
      "align": "left"
    }
  ]
}
```

`csv2xlsx --config data5.cfg -o data5.xlsx data5.csv`
